[workspace]
members = [
	"crates/mqtt-types",
	"crates/mqtt-macros",
	"crates/mqtt-client",
	"crates/entity-state",
	"crates/mqtt-provider",
	"crates/mqtt-provider-paho",
	"crates/dyn-error",

	# examples
	"examples/mqtt-light",
]
resolver = "2"
